modLoader="javafml" #mandatory
loaderVersion="[40,)"
license = "GPL-3.0"
issueTrackerURL = "https://github.com/GrowthcraftCE/Growthcraft-1.18/issues"

[[mods]]
modId = "growthcraft"
version = "7.0.0"
displayName = "Growthcraft"
updateJSONURL = "https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-Updates/master/growthcraft-versions.json"
displayURL = "https://github.com/GrowthcraftCE/Growthcraft-1.18/wiki"
logoFile = "growthcraft_core_logo.png"
credits = "Thanks to Gwafu for starting a great mod. And the Growthcraft CE Development for continuing the work."
authors = "Alatyami"
description = '''
Growthcraft is a realistic and immersive Forge mod that adds various new elements to the game of Minecraft.
'''

[[dependencies.growthcraft]] #optional
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.growthcraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

